id: P006813
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 12:24:22.665213
source_metadata:
  id: bdr:W23227
  title: གྲུབ་པའི་མཐའ་རྣམ་པར་བཤད་པའི་མཛོད།
  author: ''
  volumes:
    5c4a684d1621405f8d1ec947310d54ad:
      image_group_id: I0865
      title: ''
      volume_number: 1
      total_pages: 256
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
